# Generated by Django 4.1.7 on 2023-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(),
        ),
    ]
